name: Commitlint
on:
  push:
    branches:
      - 1.x
  pull_request:
    branches:
      - 1.x
jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.0
      - run: npm install @commitlint/cli
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
